Install wheel package alongside the upgraded 42.0.0
Since setuptools 42.0.0, the pip/wheel package is used for fetching and
building wheels whenever available - see
https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v4200
Without this change, downstream plugins are starting fail with
ERROR: 'pip wheel' requires the 'wheel' package. To fix this, run: pip install wheel